--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ColinHDev/libAsyncEvent
build-by-default: true
branches:
- main
projects:
  libAsyncEvent:
    path: ""
    model: virion
    type: library
...
